export default {
	products: [
		{
			_id: 1,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-1.jpeg',
			price: 59,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
		{
			_id: 2,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-2.jpeg',
			price: 70,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
		{
			_id: 3,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-3.webp',
			price: 60,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
		{
			_id: 4,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-4.webp',
			price: 60,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
		{
			_id: 5,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-5.webp',
			price: 60,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
		{
			_id: 6,
			name: 'Full Zip Runnig Shirts',
			category: 'Shirts',
			image: '/images/product-6.webp',
			price: 60,
			brand: 'Hiskywin',
			rating: 4.5,
			numReviews: 10,
			countInStock: 6,
		},
	],
};
